apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qytycu2qb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qytycu2qb-python 
  name: qytycu2qb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qytycu2qb-python 
